destination: ../build
highlighter: pygments
markdown: redcarpet # kramdown doesn't support ``` for code blocks
markdown_ext: "md"
name: "Art Chaidarun"
permalink: /:title.html
redcarpet:
  extensions: ["smart"]
sass:
  style: compressed
url: https://chaidarun.com
